before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- binary: netboxer
  main: ./cmd/netboxer/main.go
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
  env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  ldflags:
  - -s -w
  - -X main.name={{.ProjectName}}
  - -X main.version={{.Version}}
  - -X main.commit={{.FullCommit}}
  - -X main.date={{.Date}}
checksum:
  algorithm: sha256
archives:
- format_overrides:
  - goos: windows
    format: zip
